spring.application.name=asgard-challenge
server.port=8080

# Neon PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://ep-old-paper-alrecrzm-pooler.c-3.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_LKqPhRr9SZ8F&sslmode=require&channelBinding=require
spring.datasource.username=Roni Laufer Zukerman
spring.datasource.password=Z-q5cQECxgAa5N8

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
